import type { ClassAttribute } from '../design-classes'
import { attributeClasses, baseUtility, createClassBindings, matchesUtility } from '../design-classes'
import { cssClasses, tailwindContext } from '../tailwind-context'
import { createEslintRule } from '../utils'
import { defineTemplateBodyVisitor } from '../vue-utils'

export interface ValidClassOptions { allow?: string[], strict?: boolean }
export default createEslintRule<[ValidClassOptions?], 'invalid'>({
  name: 'vue-valid-tailwind-classes',
  meta: {
    type: 'problem',
    docs: { description: 'Check Vue classes against the site Tailwind stylesheet' },
    schema: [{ type: 'object', additionalProperties: false, properties: { strict: { type: 'boolean' }, allow: { type: 'array', items: { type: 'string' } } } }],
    messages: { invalid: '"{{className}}" is not generated by {{stylesheet}} or defined in this component. Check the class name or declare its CSS.' },
  },
  defaultOptions: [{}],
  create(context, [options = {}]) {
    const theme = tailwindContext(context.settings)
    const classes = new Set(theme.classes)
    // Vue's document fragment separates styles from strings inside script blocks.
    const services = context.sourceCode.parserServices as { getDocumentFragment?: () => { children: { type: string, name?: string, startTag?: { range: number[] }, endTag?: { range: number[] } }[] } }
    for (const element of services.getDocumentFragment?.().children ?? []) {
      if (element.type === 'VElement' && element.name === 'style' && element.startTag && element.endTag) {
        for (const name of cssClasses(context.sourceCode.text.slice(element.startTag.range[1], element.endTag.range[0])))
          classes.add(name)
      }
    }
    const bindings = createClassBindings(context.sourceCode)
    return defineTemplateBodyVisitor(context, {
      VAttribute(attribute: ClassAttribute) {
        for (const finding of attributeClasses(attribute, bindings.resolve(attribute))) {
          if (finding._tag !== 'Static')
            continue
          for (const className of finding.value.split(/\s+/).filter(Boolean)) {
            if (classes.has(className) || className === 'not-prose' || /^(?:group|peer)(?:\/[^\s:]+)?$/.test(className)
              || options.allow?.some(pattern => matchesUtility(className, pattern) || matchesUtility(baseUtility(className), pattern)) || theme.compile(className)) {
              continue
            }
            if (!options.strict && !theme.isUtility(baseUtility(className)) && !classes.has(baseUtility(className)))
              continue
            context.report({ node: finding.node, messageId: 'invalid', data: { className, stylesheet: theme.stylesheet } })
          }
        }
      },
    }, bindings.visitors)
  },
})
