// AI buzzword phrases → simpler replacements
export const BUZZWORD_PHRASES: Record<string, string> = {
  'delve into': 'explore',
  'delve deeper': 'look closer',
  'delves into': 'explores',
  'delving into': 'exploring',
  'leverage': 'use',
  'leveraging': 'using',
  'leverages': 'uses',
  'rich tapestry': 'mix',
  'tapestry of': 'mix of',
  'in the landscape of': 'in',
  'the landscape of': '',
  'evolving landscape': 'changing field',
  'ever-evolving landscape': 'changing field',
  'in today\'s landscape': 'today',
  'robust': 'strong',
  'comprehensive': 'complete',
  'cutting-edge': 'modern',
  'harness the power of': 'use',
  'harness': 'use',
  'harnessing': 'using',
  'pivotal': 'key',
  'pivotal role': 'key role',
  'streamline': 'simplify',
  'streamlining': 'simplifying',
  'streamlined': 'simplified',
  'synergy': 'combination',
  'synergies': 'combinations',
  'utilize': 'use',
  'utilizing': 'using',
  'utilizes': 'uses',
  'utilization': 'use',
  'spearhead': 'lead',
  'spearheading': 'leading',
  'game-changer': 'improvement',
  'game-changing': 'important',
  'paradigm shift': 'change',
  'paradigm-shifting': 'major',
  'unlock the potential': 'enable',
  'unlock': 'enable',
  'unlocking': 'enabling',
  'empower': 'help',
  'empowering': 'helping',
  'empowers': 'helps',
  'elevate': 'improve',
  'elevating': 'improving',
  'elevates': 'improves',
  'foster': 'encourage',
  'fostering': 'encouraging',
  'fosters': 'encourages',
  'holistic': 'complete',
  'holistic approach': 'complete approach',
  'dive into': 'look at',
  'dive deep': 'look closely',
  'realm of': 'area of',
  'in the realm of': 'in',
  'multifaceted': 'complex',
  'groundbreaking': 'new',
  'revolutionize': 'change',
  'revolutionizing': 'changing',
  'cornerstone': 'foundation',
  'seamlessly': 'smoothly',
  'seamless': 'smooth',
  'intricate': 'complex',
  'intricacies': 'details',
  'myriad': 'many',
  'myriad of': 'many',
  'plethora': 'many',
  'plethora of': 'many',
  'embark on': 'start',
  'embarking on': 'starting',
  // Self-congratulatory framing
  'headline finding': 'finding',
  'novel finding': 'finding',
  'key insight': 'insight',
  'key takeaway': 'takeaway',
  'crucial insight': 'insight',
  'important takeaway': 'takeaway',
  'notable finding': 'finding',
  'remarkable finding': 'finding',
  'striking finding': 'finding',
  // Textbook phrasing
  'it turns out that': '',
  'as it turns out': '',
  'what this means is': '',
  'what this tells us is': '',
  'the takeaway here is': '',
  'the key here is': '',
  'the important thing to note is': '',
  'the reality is': '',
  'the truth is': '',
  'the question becomes': '',
  'the answer lies in': '',
  // PR language
  'no configuration needed': 'zero-config',
  'out of the box': 'by default',
  'just works': 'works',
  'best-in-class': 'strong',
  'world-class': 'high-quality',
  'state-of-the-art': 'modern',
  'next-generation': 'new',
  'industry-leading': 'leading',
  'paramount': 'key',
  'fundamental': 'basic',
  'underlying': 'basic',
  'integral': 'key',
  'testament to': 'shows',
  'beacon of': 'example of',
  'unleash': 'use',
  'demystify': 'explain',
  'comprehensive guide': 'guide',
  'step-by-step guide': 'guide',
  'tackle challenges': 'solve problems',
  'tackling challenges': 'solving problems',
  // Copywriting: simple over complex
  'facilitate': 'help',
  'facilitating': 'helping',
  'facilitates': 'helps',
  'innovative': 'new',
  'methodology': 'method',
  'methodologies': 'methods',
  'incentivize': 'encourage',
  'incentivizing': 'encouraging',
}

// Filler sentences/phrases that can be removed entirely
export const FILLER_PHRASES: string[] = [
  'it\'s worth noting that',
  'it is worth noting that',
  'it\'s important to note that',
  'it is important to note that',
  'it\'s worth mentioning that',
  'it is worth mentioning that',
  'it goes without saying that',
  'needless to say',
  'in today\'s world',
  'in today\'s digital age',
  'in today\'s fast-paced world',
  'in the ever-evolving landscape of',
  'in an ever-changing world',
  'as we navigate the complexities of',
  'as we navigate',
  'at the end of the day',
  'when it comes to',
  'when all is said and done',
  'the fact of the matter is',
  'it should come as no surprise that',
  'without a doubt',
  'there is no denying that',
  'there\'s no denying that',
  'as a matter of fact',
  'it\'s no secret that',
  'it is no secret that',
  'let\'s face it',
  'to be honest',
  'truth be told',
  'make no mistake',
  'the bottom line is',
  'at its core',
  'in a nutshell',
  // Defensive hedging
  'this isn\'t as contradictory as it looks',
  'this isn\'t as contradictory as it sounds',
  'these aren\'t theoretical problems',
  'these aren\'t just theoretical',
  'this might sound counterintuitive but',
  'this may seem counterintuitive but',
  'contrary to popular belief',
  'you might be wondering',
  'you may be wondering',
  'you might think that',
  'you may think that',
  'before you dismiss this',
  'hear me out',
  'bear with me',
  // Textbook setup
  'let\'s break this down',
  'let\'s unpack this',
  'let\'s take a closer look',
  'let\'s explore this further',
  'let\'s dig deeper',
  'let\'s examine',
  'let\'s dive in',
  'let\'s get started',
  'let\'s take a look',
  'let\'s see how this works',
  'let\'s move on to',
  'to put it simply',
  'to put it another way',
  'in other words',
  'simply put',
  'put simply',
  'here\'s the thing',
  'here\'s the kicker',
  'here\'s where it gets interesting',
  'here\'s where things get interesting',
  'but here\'s the catch',
  'but here\'s the thing',
  'spoiler alert',
  // Robot speech / Over-politeness
  'as an AI language model',
  'i hope this helps',
  'please let me know if you have any other questions',
  'should you have any further questions',
  'please feel free to ask',
  'feel free to reach out',
  // Transition words that are often filler
  'furthermore',
  'moreover',
  'consequently',
  'subsequently',
  'additionally',
  'in summary',
  'to summarize',
  'to sum up',
]

// Unnecessary adverbs that add no meaning
export const UNNECESSARY_ADVERBS: string[] = [
  'significantly',
  'fundamentally',
  'essentially',
  'literally',
  'dramatically',
  'incredibly',
  'remarkably',
  'undeniably',
  'undoubtedly',
  'unquestionably',
  'tremendously',
  'exceptionally',
  'extraordinarily',
  'profoundly',
  'vastly',
  'immensely',
  'crucially',
  'ultimately',
  'inherently',
  'arguably',
  'actually',
  'basically',
  'clearly',
  'obviously',
  'definitely',
  'totally',
  'absolutely',
  'completely',
  'entirely',
  'fully',
  'perfectly',
]

// Hedging/qualifying words that weaken copy
export const HEDGING_WORDS: string[] = [
  'very',
  'really',
  'quite',
  'somewhat',
  'fairly',
  'rather',
  'slightly',
  'a bit',
  'a little',
  'just',
  'almost',
  'mostly',
  'largely',
  'practically',
  'nearly',
]

export const CONTENT_FILES = ['**/content/**/*.md', '**/docs/**/*.md', '**/README.md']
